export const AppImages = {
  COUNTRY_CODE: require("../assets/images/country_code.png"),
  DOCUMENT_REVIEW: require("../assets/images/document_review.png"),
  FRAME_YOUR_FACE: require("../assets/images/frame_your_face.png"),
  GOOGLE_ICON: require("../assets/images/google_icon.png"),
  LOGO_STACKED: require("../assets/images/logo_stacked.png"),
  LOGO: require("../assets/images/logo.png"),
  MASTER_CARD: require("../assets/images/master_card.png"),
  PROFILE_CREATION: require("../assets/images/profile_creation.png"),
  START_JOURNEY: require("../assets/images/start_journey.png"),
  USER_CHRISTY: require("../assets/images/user_christy.png"),
  USER_LARRY: require("../assets/images/user_larry.png"),
  USER_MARCELINA: require("../assets/images/user_marcelina.png"),
  VERIFY_PROFILE: require("../assets/images/verify_profile.png"),
  GET_STARTED_HEADER: require("../assets/images/get_started_header.png"),
  LOGO_BLACK: require("../assets/images/logo_black.png"),
  USER_PHOTOS: require("../assets/images/user_photos.jpg"),
  MATCHED_USER_ONE: require("../assets/images/matched_user_one.jpg"),
  MATCHED_USER_TWO: require("../assets/images/matched_user_two.jpg"),
  BOOSTING: require("../assets/images/boosting.png"),
  CHECK: require("../assets/images/check.png"),
  FILTER_ICON: require("../assets/images/filter_icon.png"),
};
